# HousingRegression/.github/workflows/ci.yml

name: CI Pipeline for Regression Models

on:
  push:
    branches:
      - reg_branch
      - main
      - hyper_branch

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python environment
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Regression Script
      run: |
        python regression.py